#!/usr/bin/env sh


#-----------HEAD-------------------------------------------------------------->
# Matheus Martins 3mhenrique@gmail.com
# https://github.com/mateuscomh 
# 08/06/2021
# Shell-Base
# v1.1 - GPL3
# REQ: ngrok-client/sed/curl
# Expose local port on service ngrok - useful for behind CGNAT
#
# 08/06/2021 - From bobmarksie 
# 08/12/2021 - Update head
#-----------END-HEAD-----------------------------------------------------------<

echo "Stopping background ngrok process"
sleep 1
kill -9 "$(pgrep "ngrok")" && /
#kill -9 "$(ps -ef | grep 'ngrok' | grep -v 'grep' | awk '{print $2}')" && /
echo "ngrok stopped" || echo "nothing to do"
