#!/usr/bin/env sh

#-----------HEAD-------------------------------------------------------------->
# AUTOR             : Matheus Martins 3mhenrique@gmail.com
# HOMEPAGE          : https://github.com/mateuscomh 
# DATA CRIAÇÃO      : 08/06/2021
# PROGRAMA          : Shell-Base
# VERSÃO            : 1.0.0
# LICENÇA           : GPL3
# REQUISITOS        : Necessário serviço ngrok server instalado
# PEQUENA-DESCRIÇÃO : Programa para inicializar ngrok simulando serviço em 
# segundo plano.
#
# CHANGELOG         : 08/06/2021 10:00 - Adequado de bobmarksie 
#
#-----------END-HEAD-----------------------------------------------------------<

# Set local port from command line arg or default to 8080
LOCAL_PORT=${8080-8080}

echo "Start ngrok in background on port [ $LOCAL_PORT ]"
nohup ngrok http "${LOCAL_PORT}" &>/dev/null &

echo -n "Extracting ngrok public url ."
NGROK_PUBLIC_URL=""
while [ -z "$NGROK_PUBLIC_URL" ]; do
  # Run 'curl' against ngrok API and extract public (using 'sed' command)
  NGROK_PUBLIC_URL=$(curl --silent --max-time 10 --connect-timeout 5 \
                            --show-error http://127.0.0.1:4040/api/tunnels | \
                            sed -nE 's/.*public_url":"https:..([^"]*).*/\1/p')
  export NGROK_PUBLIC_URL
  sleep 3
  echo -n "."
done

echo
echo "NGROK_PUBLIC_URL => [ $NGROK_PUBLIC_URL ]"
