#!/usr/bin/env sh

#-----------HEAD-------------------------------------------------------------->
# Matheus Martins 3mhenrique@gmail.com
# https://github.com/mateuscomh 
# 08/06/2021
# Shell-Base
# v1.1 - GPL3
# REQ: ngrok-client/sed/curl
# Expose local port on service ngrok - useful for behind CGNAT
#
# 08/06/2021 - Adequado de bobmarksie 
# 08/12/2021 - Upddate head
#-----------END-HEAD-----------------------------------------------------------<

# Set local port from command line arg or default to 8080
LOCAL_PORT=${8080-8080}

echo "Start ngrok in background on port [ $LOCAL_PORT ]"
nohup ngrok http "${LOCAL_PORT}" &>/dev/null &

echo -n "Extracting ngrok public url ."
NGROK_PUBLIC_URL=""
while [ -z "$NGROK_PUBLIC_URL" ]; do
  # Run 'curl' against ngrok API and extract public (using 'sed' command)
  NGROK_PUBLIC_URL=$(curl --silent --max-time 10 --connect-timeout 5 \
                            --show-error http://127.0.0.1:4040/api/tunnels | \
                            sed -nE 's/.*public_url":"https:..([^"]*).*/\1/p')
  export NGROK_PUBLIC_URL
  sleep 3
  echo -n "."
done
echo "NGROK_PUBLIC_URL => [ $NGROK_PUBLIC_URL ]"
